import type { Metadata } from "next";
import { Rubik, Geist_Mono } from "next/font/google";
import "./globals.css";

const fontRubik = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${fontRubik.variable} ${geistMono.variable} antialiased h-screen w-screen`}
            >
                <div className="relative h-full w-full bg-with-opacity">
                    {children}
                </div>
            </body>
        </html>
    );
}
